### ISSUE TITLE
it fetches sidekiq option as table and column

### ISSUE THREAD

**Issue by rubyconvict** [gregnavis/active_record_doctor#6] opened 2016-06-20 12:17 UTC
```cat unindexed_foreign_keys.txt```
```
Sidekiq concurrency: 25
membership_roles inherited_from_id
memberships member_id
projects parent_id
```

```cat config/sidekiq.yml```
```
---
:concurrency: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
(...omitted...)
```

**Comment by gregnavis** [comment] 2016-06-21 08:09
@rubyconvict thanks for reporting. Will take care of this soon.

**Comment by gregnavis** [comment] 2016-08-16 09:51
@rubyconvict I'm not able to reproduce the problem. My hypothesis is that the first line (`Sidekiq concurrency: 25`) is printed during initialization by your app. The only places where anything is printed are in [`io_printer.rb`](https://github.com/gregnavis/active_record_doctor/blob/62f4fe9727834b9efb321b4fb3ce32418316487b/lib/active_record_doctor/printers/io_printer.rb) and none of them could print the problematic line.

Could you verify that your app is not the source of the first line of output?

**Comment by rubyconvict** [comment] 2016-08-17 08:00
Indeed, this is causing the problem, but the gem's behaviour is reckless...

```cat config/initializers/sidekiq.rb```
```
(...omitted...)
if Rails.env.development?
  puts "Sidekiq concurrency: #{Sidekiq.options[:concurrency]}"
end
```

**Comment by gregnavis** [comment] 2016-08-17 09:24
@rubyconvict could you clarify what you mean by _reckless_? I want to be sure I understand your use case correctly so could you provide an example of how you think it should work? Thanks.

**Comment by rubyconvict** [comment] 2016-08-17 13:57
Sorry, for my english, what I meant to say is that maybe including unexpected `puts` output from an initializer or from wherever it might come from, should be avoided at all cost, STDOUT can be tricky.

**Comment by gregnavis** [comment] 2016-08-23 08:40
@rubyconvict Yes, this is a good point. An alternative approach I considered was to specify a file name where the results would be written. However, I opted for a simpler approach of using stdout and redirection.

I think I'd like to keep this simpler approach for now and focus on building more features but will certainly consider alternatives in the future. I'm closing this issue as it's not actionable right now. Thanks for reporting and if you spot anything fishy feel free to report another issue.

**Closed by gregnavis** 2016-08-23 08:40 UTC
